version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: process.env.DOCKER_PASSWORD
      MYSQL_DATABASE: StoreDataBase
    ports:
      - "3306:3306"